os: windows
language: shell

before_install:
    - choco install python --version 3.7.5
    - python --version
    - python -m pip install --upgrade pip
env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install: pip3 install -r requirements.txt -r requirements-test.txt
script: pytest