trigger:
- master

pool: windows-vms

steps:

- powershell: |
    choco install python --version 3.7.5
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- powershell: |
    pip install -U pytest pytest-azurepipelines
    pytest -v
  displayName: 'Run Tests'