trigger:
- master

pool: windows-vms

steps:

- powershell: |
    choco install python -y --version 3.7.5
    SET PATH=/c/Python37:/c/Python37/Scripts:$PATH
    refreshenv
    python -m pip install --upgrade pip
    pip install -r requirements-test.txt
  displayName: 'Install dependencies'

- powershell: |
    pip install -U pytest pytest-azurepipelines
    pytest -v
  displayName: 'Run Tests'