trigger:
- master

variables:
  python376: C:\Python37\python.exe
  pip376: C:\Python37\Scripts\pip.exe
  pytest376: C:\Python37\Scripts\pytest.exe
  

jobs:
- job: setup_env
  displayName: 'Setup Environment'
  strategy:
    matrix:
      Server2019:
        AGENT_NAME: 'AZ-SERVER2019'
      Server2016:
        AGENT_NAME: 'AZ-SERVER2016'
      Windows10:
        AGENT_NAME: 'AZ-WIN10'
      Server2012R2:
        AGENT_NAME: 'AZ-WIN2012R2'
      Windows81:
        AGENT_NAME: 'AZ-WIN81'
  
  pool:
    name: windows-vms
  
  steps:
  - script: |
      $(python376) -m pip install --upgrade pip
      $(pip376) install -r requirements-test.txt
    displayName: 'Install dependencies'

  - script: |
      $(pip376) install -U pytest pytest-azurepipelines
      $(pytest376) -v
    displayName: 'Run Tests'