trigger:
- azure-test

strategy:
  matrix:
    win2019:
      imageName: 'windows-2019'
    win2016:
      imageName: 'vs2017-win2016'
    win2012R2:
      imageName: 'vs2015-win2012r2'

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
  displayName: 'Use Python 3.7'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements-test.txt
  displayName: 'Install dependencies'

- script: |
    pip install -U pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
